### ISSUE TITLE
Looking for advices on this particular graphics

### ISSUE THREAD

**Issue by Shin-Huang** [Shin-Huang/Local-Peace-Agreement#1]
Not too sure about what to put into the background to fill out the blank space. It looks a bit plain to me but I don't want to over-complicated the visual aspect... (The inspiration was from the Hama water wheel in Syria as it was one of the focus on our inspection.)
![Agreement Definition and Statement](https://user-images.githubusercontent.com/53304481/100529889-b6414480-31e3-11eb-9798-149307b390ac.png)
![2](https://user-images.githubusercontent.com/53304481/100529891-bf321600-31e3-11eb-841f-eea3a08b76eb.png)

**Comment by Shin-Huang** [comment]
![Hama_waterWheels1](https://user-images.githubusercontent.com/53304481/100529938-1a640880-31e4-11eb-9d0e-4c1b3b9430da.jpg)
![Hama_waterWheels2](https://user-images.githubusercontent.com/53304481/100529940-1b953580-31e4-11eb-8f54-086009d7eb18.jpg)
![Hama_waterWheels3](https://user-images.githubusercontent.com/53304481/100529941-1b953580-31e4-11eb-9e04-2197172a45cb.jpg)
Photo Reference

**Comment by Shin-Huang** [comment]
Here comes with the 2nd data analysis. Please leave any feedback and comments below.
![Agreement Definition and Status Region](https://user-images.githubusercontent.com/53304481/100530226-29988580-31e7-11eb-9fe3-2bdd1bb0d274.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/53304481/100530228-2f8e6680-31e7-11eb-9593-aba4eba52d08.png)

**Comment by TerryQu1997** [comment]
Wow, very cool. These are scatter plots, right? If you can actually add a translucent line to connect the data, is it like a line chart again? Just a thought.lol, I have to say it's a very good idea.

**Comment by Shin-Huang** [comment]
Hello Terry, thank you so much. It definitely encouraging me to do more on this part and I have came up with a solution before I went to bed. Later on I will update these two graphs continuously on this thread. 

By adding a translucent line to connect the data, would you please provide me with an example? You've mentioned about line chart, do you want me to make two separate line charts for each of these two graphs?

**Comment by Shin-Huang** [comment]
This is the update for the new version based on team's decision: 
The final visualization style in the overview report part which will apply into other section as well.

![Color Templates](https://user-images.githubusercontent.com/53304481/100921369-60ff7e80-34d4-11eb-9d6e-9e9ecd8e40d7.png)

**Comment by Shin-Huang** [comment]
According to the new decision on the visual style the team decided on, here are the color-codes we selected off:
1. f47d7d
2. 35475c
3. df5f5b 
4. 207dc9
5. ffa015
![colorComp](https://user-images.githubusercontent.com/53304481/100922049-48dc2f00-34d5-11eb-980f-48769c22981a.png)

**Comment by Shin-Huang** [comment]
Here are the "Overview Analysis" dataset provided by QU Wenzheng ,HUANG Shin-Yi and XIA Sandra.

![Mediator_ContP](https://user-images.githubusercontent.com/53304481/100922229-8e006100-34d5-11eb-8ad9-d009da95156e.png)
![Mediators on Grievances](https://user-images.githubusercontent.com/53304481/100922232-8f318e00-34d5-11eb-81af-1d4749d21ca3.png)
![PT_Area](https://user-images.githubusercontent.com/53304481/100922234-8f318e00-34d5-11eb-81eb-68ce13e7f1e9.png)
![PT_Year](https://user-images.githubusercontent.com/53304481/100922235-8fca2480-34d5-11eb-96ee-89f597e48215.png)
![Separate Report_1-1](https://user-images.githubusercontent.com/53304481/100922236-8fca2480-34d5-11eb-9450-3c35e052571a.png)
![StatusDate](https://user-images.githubusercontent.com/53304481/100922237-9062bb00-34d5-11eb-9cfe-e07c36e3d39b.png)
![StatusRegion](https://user-images.githubusercontent.com/53304481/100922239-9062bb00-34d5-11eb-966c-00c9d5ece788.png)
![LatitudeContries](https://user-images.githubusercontent.com/53304481/100922240-90fb5180-34d5-11eb-9dc3-866e3597ff7e.png)
![LongitudeContries](https://user-images.githubusercontent.com/53304481/100922244-90fb5180-34d5-11eb-8c7e-ea36c92448d4.png)

**Comment by Shin-Huang** [comment]
According to XIA Sandra's feedback, she suggested to use simple circles instead of water wheels in the bar chart, for the water wheel icon in the overview part.

Therefore, here are the final replacements:
![Group 42](https://user-images.githubusercontent.com/53304481/100922525-e9325380-34d5-11eb-8b0a-1df65af0de54.png)
![Group 49](https://user-images.githubusercontent.com/53304481/100922526-e9caea00-34d5-11eb-8f01-cbaa58629a22.png)
![Group 50](https://user-images.githubusercontent.com/53304481/100922527-e9caea00-34d5-11eb-9d65-3cdcd734fc4a.png)

**Comment by Dora-wang777** [comment]
the pictures are really cool!  the color and the size is nice!
