### ISSUE TITLE
Analysis of the influence of culture and economy on the types of mediators

### ISSUE THREAD

**Issue by Dora-wang777** [Shin-Huang/Local-Peace-Agreement#11]
[Analysis of the influence of culture and economy on the types of mediators.pdf](https://github.com/Shin-Huang/Local-Peace-Agreement/files/5647211/Analysis.of.the.influence.of.culture.and.economy.on.the.types.of.mediators.pdf)

**Comment by Dora-wang777** [comment]
Hi guys, this is an analysis of mediator type. 
I hope you could give me some advice～

**Comment by Xiashuxin** [comment]
It's great! The hypothesis, culture and economy could affect type of mediators is very funny.
