### ISSUE TITLE
The understanding of "Grieve: Grievances" column

### ISSUE THREAD

**Issue by Xiashuxin** [Shin-Huang/Local-Peace-Agreement#12]
I found we might misunderstand the column "Grieve". We first thought it is about the satisfaction of local peace agreements, however, after checking our codebook, I think it probably means whether there is evidence about grievance, here is an example.
Example: Page 4, Grievances of SPLA-IO Yei River State, 1. Country-wide insecurity which is a sign of total breakdown of security 2. Ongoing uncalled for targeted killings of our brothers/sisters/mothers and fathers 3. Failure of the Judicial system leading to rise in cases of land grabbing and malpractice 4. Deliberate promotion of hate speech, tribalism, nepotism, partisan politics and lack of space for political opposition by the government 5. Continuous appointment of unpopular politicians in our region leading to a calculated misguidance, hence a failure to govern the populace

**Comment by TerryQu1997** [comment]
Yes, that was a really good question. I did misunderstand the concept of "Grieve", which was a lot of useless analysis I did, for example I analyzed the relationship between Grieve and the mediator, and I'll look at that next time.
