### ISSUE TITLE
Analysis on the number of local peace agreements

### ISSUE THREAD

**Issue by Xiashuxin** [Shin-Huang/Local-Peace-Agreement#13]
[readme.docx](https://github.com/Shin-Huang/Local-Peace-Agreement/files/5647246/readme.docx)

**Comment by Xiashuxin** [comment]
This part is based on these three hypotheses:
Increase in the number of local peace agreements means more conflicts.
Increase in the number of local peace agreements means stronger peace consciousness and prediction of peace.
Number of local peace agreements have no relate directly to conflicts.

**Comment by Xiashuxin** [comment]
You could have a look at it, and give me some advice.

**Comment by qiaoyue211** [comment]
I think we can make a timeline with important timepoint and figure the relationships between the number of peace agreements signed based on countries.

**Comment by qiaoyue211** [comment]
For exmaple, I could see peaks of percentage of local peace agreements usually mean the beginning of wars or a new stage of wars.

**Comment by Shin-Huang** [comment]
In addition to this, gather some researches from real life to try to investigate what actually caused these peaks of local peace agreements. The source can be found from internet, newspaper and such. It could be useful to help us add more content into our creation and report later on.

**Comment by SandraXia** [comment]
> I think we can make a timeline with important timepoint and figure the relationships between the number of peace agreements signed based on countries.

Yes! I choose four important timepoints in four main countries to see the result

**Comment by SandraXia** [comment]
> In addition to this, gather some researches from real life to try to investigate what actually caused these peaks of local peace agreements. The source can be found from internet, newspaper and such. It could be useful to help us add more content into our creation and report later on.

Very useful! And these also could be shown in our website to support our analysis.
