### ISSUE TITLE
Shall we use conflicts dataset? 

### ISSUE THREAD

**Issue by SandraXia** [Shin-Huang/Local-Peace-Agreement#15]
Because I think it could make our analysis more convincing, and maybe we could find the relationship between local peace agreements and the whole peace process.

**Comment by Shin-Huang** [comment]
That's actually a very good point. Try to speculate the data from a different perspective by examining another different dataset. It would help us understand that whether there's a direct relationship between local peace agreement in the whole peace process or not!

**Comment by SandraXia** [comment]
I found this website about all conflicts but didn't find any dataset on local conflicts. So maybe we can't use the data for comparison, but still, we could use this to know more about conflicts and the whole region's peace process. a/ [https://www.prio.org/Data/Armed-Conflict/Armed-Conflict-Location-and-Event-Data/ ](URL) 
[https://ucdp.uu.se/](URL)
