### ISSUE TITLE
Updates for Graph2-6

### ISSUE THREAD

**Issue by Shin-Huang** [Shin-Huang/Local-Peace-Agreement#3]
The graph for sum of local peace agreements based on countries. Looking for suggestions for potential improvements.
1. number of local peace agreements in four countries in time order
![graph2](https://user-images.githubusercontent.com/53304481/100558243-8eb2b080-32a5-11eb-936a-62769df71229.png)
![image](https://user-images.githubusercontent.com/53304481/100560302-4dbe9a00-32ad-11eb-8f7a-dc4efb3993d6.png)

2. number of local peace agreements in four countries in time order
![graph3](https://user-images.githubusercontent.com/53304481/100558262-a1c58080-32a5-11eb-8765-ec4268399d0a.png)
![image](https://user-images.githubusercontent.com/53304481/100560311-531be480-32ad-11eb-9301-d476353a1f4e.png)

**Comment by Shin-Huang** [comment]
3. number of all peace agreements in four countries after 2011
![graph3](https://user-images.githubusercontent.com/53304481/100560367-7c3c7500-32ad-11eb-995c-0bf1a3b91219.png)
![image](https://user-images.githubusercontent.com/53304481/100560419-a68e3280-32ad-11eb-8f1d-75ef068765ab.png)

4. distribution of local peace agreements in all peace agreements
![graph5](https://user-images.githubusercontent.com/53304481/100560484-d63d3a80-32ad-11eb-9760-6b2871696a27.png)
![image](https://user-images.githubusercontent.com/53304481/100560444-b574e500-32ad-11eb-83b7-7626f9da2daf.png)

**Comment by Shin-Huang** [comment]
5. The percentage of local peace agreements with mediators
![graph6](https://user-images.githubusercontent.com/53304481/100562081-77c68b00-32b2-11eb-9211-10d6bb43e5a0.png)
![image](https://user-images.githubusercontent.com/53304481/100562088-7ac17b80-32b2-11eb-8ea8-eed01b950170.png)

**Comment by Dora-wang777** [comment]
cool, like a game

**Comment by Shin-Huang** [comment]
Collected the overall feedback, the team decided to simplify the styles of graph 2 to 6 in general. Therefore, I followed the new instructions and designed a new graphic style for these graphs.

![Separate Report_1-1 – 2](https://user-images.githubusercontent.com/53304481/100924928-35cb5e00-34d9-11eb-9e93-d927b3a89783.png)
![Separate Report_1-1 – 3](https://user-images.githubusercontent.com/53304481/100924933-3663f480-34d9-11eb-9cd1-9f0743e2ee8e.png)
![Separate Report_1-1 – 4](https://user-images.githubusercontent.com/53304481/100924934-36fc8b00-34d9-11eb-9ccd-6a5a7412971e.png)
![Separate Report_1-1 – 5](https://user-images.githubusercontent.com/53304481/100924936-36fc8b00-34d9-11eb-8c26-07d79fd296e6.png)
![Separate Report_1-1 – 6](https://user-images.githubusercontent.com/53304481/100924941-37952180-34d9-11eb-8819-b2505302deae.png)
![Separate Report_1-1](https://user-images.githubusercontent.com/53304481/100924943-382db800-34d9-11eb-98f8-de6d2eb6a3f5.png)

**Comment by Shin-Huang** [comment]
Adding the explicit gradient color for the background color I used:
1.C2937
2.F475F

**Comment by Shin-Huang** [comment]
Adding the explicit gradient color for the background color I used:
1.C2937
2.F475F
