### ISSUE TITLE
colud you give me  a title and  a description for each picture of yours

### ISSUE THREAD

**Issue by Dora-wang777** [Shin-Huang/Local-Peace-Agreement#4]
![LatitudeContries](https://user-images.githubusercontent.com/73389959/100989024-53f19680-358b-11eb-97c0-0026f6701449.png)
![LongitudeContries](https://user-images.githubusercontent.com/73389959/100989035-56ec8700-358b-11eb-966a-f46942fcec4b.png)

**Comment by Shin-Huang** [comment]
The title: "The location of each country by longitude and latitude"

Analysis (description): To have a thorough visualization on each countries that were mentioned in the local peace agreement in terms of their location determined by longitude and latitude, there are two graphs individually being visualized based on the longitude and the Latitude variables. As we observe from these graphs, the majority of the countries are located around the equator.
