### ISSUE TITLE
Review on Final Report

### ISSUE THREAD

**Issue by Shin-Huang** [Shin-Huang/Local-Peace-Agreement#5]
Please take a look at the final report for our Local Peace Agreement. The word count currently is exceeded 1000 words from the requirement, please feel free to edit this paper. Be mindful that I have citation most of the resources that was mentioned in Xia's analysis, although it is necessary to input the citation as '[6]' for this dataset in particular within this report. 

(The overall report was mainly based on QU, Xia's analysis and the information from today's presentation Miro board. )

@Shin-Huang @Dora-wang777 @TerryQu1997 @SandraXia 

[Local Peace Agreement Report.docx](https://github.com/Shin-Huang/Local-Peace-Agreement/files/5639845/Local.Peace.Agreement.Report.docx)
[Local Peace Agreement Report.pdf](https://github.com/Shin-Huang/Local-Peace-Agreement/files/5639846/Local.Peace.Agreement.Report.pdf)

**Comment by Dora-wang777** [comment]
it is helpful! thanks, my friend

**Comment by Dora-wang777** [comment]
I think we need to put our research into our report!

**Comment by qiaoyue211** [comment]
Excellent work!!! I think it is a good final report! I also wrote some words according to our presentation and miro, you could look at it and add sth in the report. There is some duplication between them so you could just ignore it and choose what is useful to use as you like.
[DS4D.docx](https://github.com/Shin-Huang/Local-Peace-Agreement/files/5641239/DS4D.docx)

**Comment by qiaoyue211** [comment]
One more thing is the citation format, I need transfer all the citation format into Harvard.

**Comment by Shin-Huang** [comment]
> Excellent work!!! I think it is a good final report! I also wrote some words according to our presentation and miro, you could look at it and add sth in the report. There is some duplication between them so you could just ignore it and choose what is useful to use as you like.
> [DS4D.docx](https://github.com/Shin-Huang/Local-Peace-Agreement/files/5641239/DS4D.docx)

Just want to confirm that are you taking over on editing the report? Most of the contents were based off our presentation and from the miro board, therefore.

**Comment by Shin-Huang** [comment]
> One more thing is the citation format, I need transfer all the citation format into Harvard.

There is no specific formatting on the citation for this report, I believe. Although if you prefer to put them in Harvard style, I'm fine with that. Just be mindful that it would take some time to edit them.

**Comment by Shin-Huang** [comment]
> I think we need to put our research into our report!

I have tried to implemented all of our individual researches into the report. Although it has exceeded 1000 words already including QU's analysis and did not even cover the entire context from Xia's. According to the textbook of DSWD, it requires us to conduct our researches that are NOT included in our creation (a.k.a our website) Which is why I am asking you folks to "tidy it up" if everyone could take a look at it.

![1](https://user-images.githubusercontent.com/53304481/101217670-ac06c680-3679-11eb-9a07-68b5c9c6a89e.JPG)

**Comment by Shin-Huang** [comment]
Someone post a question regarding to the final report on Teams and Ben replied back to him as following: 
![Screenshot_20201205_051208_com microsoft teams](https://user-images.githubusercontent.com/53304481/101234587-a11f5680-36b8-11eb-823f-5f6669b431de.jpg)
![Uploading Screenshot_20201128_013425_com.google.android.googlequicksearchbox.jpg…]()

**Comment by TerryQu1997** [comment]
It's a good report, but I think there are some quotes that haven't been flagged, and the second paragraph is some quotes from the web that we need to flag, and I'll try to find that web page.
