### ISSUE TITLE
storyboard

### ISSUE THREAD

**Issue by Dora-wang777** [Shin-Huang/Local-Peace-Agreement#7]
![1](https://user-images.githubusercontent.com/73389959/101244392-41b95900-3741-11eb-9cd5-d49e7c9cc9ff.png)

**Comment by Dora-wang777** [comment]
This is our storyboard if you have any idea, please take some comments here.

**Comment by Dora-wang777** [comment]
![2](https://user-images.githubusercontent.com/73389959/101245127-a70f4900-3745-11eb-89e9-e588769390d4.png)
what do you think about the reminder?

**Comment by Dora-wang777** [comment]
![3](https://user-images.githubusercontent.com/73389959/101245181-eb9ae480-3745-11eb-9f83-edb681bb26a9.png)
You can zoom in and zoom out the website！

**Comment by TerryQu1997** [comment]
I think it's great that we can just put this in our Github file as a record of our initial work.

**Comment by Xiashuxin** [comment]
![Uploading 4.1.png…]()

**Comment by Xiashuxin** [comment]
![Uploading 6.1.png…]()

**Comment by qiaoyue211** [comment]
The storyboard need some more details to show our idea.

**Comment by qiaoyue211** [comment]
This is also a useful page for our project
![7](https://user-images.githubusercontent.com/74944303/101245557-b348d580-3748-11eb-8b52-3d3ddd622cdd.png)

**Comment by qiaoyue211** [comment]
Plus this one
![5](https://user-images.githubusercontent.com/74944303/101245578-d1163a80-3748-11eb-9e62-49e4689639cb.png)

**Comment by Xiashuxin** [comment]
![Uploading 4.1.png…]()

**Comment by Xiashuxin** [comment]
![4 1](https://user-images.githubusercontent.com/49523396/101246525-e7bf9000-374e-11eb-8c1e-94f785b0f9a9.png)

**Comment by Xiashuxin** [comment]
![6 1](https://user-images.githubusercontent.com/49523396/101246534-f1e18e80-374e-11eb-8153-bdbf361de3d2.png)

**Comment by Shin-Huang** [comment]
This is one of my idea for the early concept which is contained the data analysis from my part. I thought it could be discussed whether to add it in into our creation later on or not. Please take a look at it and let me know your thought:
![Group13_sketch](https://user-images.githubusercontent.com/53304481/101260407-92bc5380-3727-11eb-9bbe-67bbc2628c55.jpg)
![Group13_sketch2](https://user-images.githubusercontent.com/53304481/101260409-95b74400-3727-11eb-997f-4121cb08b543.jpg)
![IMG_20201109_101905](https://user-images.githubusercontent.com/53304481/101260411-96e87100-3727-11eb-89f4-2ba9251f8458.jpg)
![Syria – 1](https://user-images.githubusercontent.com/53304481/101260412-98b23480-3727-11eb-8f24-9fa3d4a25172.png)
