### ISSUE TITLE
The final video about local peace agreement

### ISSUE THREAD

**Issue by TerryQu1997** [Shin-Huang/Local-Peace-Agreement#8]
Hi, guys, https://youtu.be/I6JvIOWEdXc that's youtube's link about our video.
I've also written some introductions for it, and if you think there's anything wrong with the introduction or the video content or even the background music, you can comment, and we'll discuss whether or not to change it.

**Comment by Dora-wang777** [comment]
Wow, the video is so cool!
I like the website! The colour, the interaction, the analysis.
The music sounds great！

**Comment by Shin-Huang** [comment]
This looks fantastic! The resolution is high so very clear for people to see. The new version of music suits our theme perfectly. Well done!
