### ISSUE TITLE
Please help to check the website

### ISSUE THREAD

**Issue by TerryQu1997** [Shin-Huang/Local-Peace-Agreement#9]
http://107.151.193.203/ct/ 
his is our website link, guys, can you help me check what problems exist in our website? If you have any questions please feel free to comment.

**Comment by Dora-wang777** [comment]
![WechatIMG649](https://user-images.githubusercontent.com/73389959/101245787-46ced600-374a-11eb-87cf-2a5d707935a4.png)
the size of the picture is too big I think!
Could you change it？

**Comment by Dora-wang777** [comment]
![WechatIMG650](https://user-images.githubusercontent.com/73389959/101245851-b1801180-374a-11eb-9ec7-d40c5fcb3c15.png)
Can you change the font？

**Comment by TerryQu1997** [comment]
Yes, the picture is really too big, I have adjusted it, you can reopen the page and have a look, the font I see here is different from yours, this may be due to the browser problem, At present I have not come up with a suitable solution, I will optimize it in the future.

**Comment by qiaoyue211** [comment]
In addition, there is explicit information organized that displayed on the slide by clicking on our Analysis Report. Users will learn about specific analyses of mediators and local peace agreements.
